korpus_data = {
    0 : "Perangkat Lunak (software) merupakan data elektronik yang disimpan sedemikian rupa oleh komputer itu sendiri, data yang disimpan ini dapat berupa program atau instruksi yang akan dijalankan oleh perintah, maupun catatan-catatan yang diperlukan oleh komputer untuk menjalankan perintah yang dijalankannya.",
    1 : "Metode SDLC (Software Development Life Cycle) adalah proses pembuatan dan pengubahan sistem serta model dan metodologi yang digunakan untuk mengembangkan sistem rekayasa perangkat lunak.",
    2 : "Komputer adalah mesin penghitung eletronik yg cepat dapat menerima informasi input digital, memprosesnya sesuai dengan suatu program yang tersimpan di memorinya dan menghasilkan output informasi. Jadi dapat disimpulkan bahwa komputer adalah sekelompok alat elektronik yang terdiri atas perintah input, alat yang mengolah input, dan peralatan output yang memberikan informasi serta bekerja secara otomatis.",
    3 : "Program Studi S1 Rekayasa Perangkat Lunak adalah salah satu program studi yang berada di Kampus UPI di Cibiru yang berlokasi di Jl. Raya Cibiru KM 15 Kabupaten Bandung. Di dalam Program Studi Rekayasa Perangkat lunak, mahasiswa akan mempelajari bidang ilmu terkait Software Engineering (pengembangan software, manajemen software, proses engineering, perangkat engineering dan metodologi), Data Engineering (data modelling, manajemen data berbasis pengetahuan, penerapan manajemen data), Pemrograman Multimedia & Game (Game Development, animasi 2D & 3D), dan Ubiquitous Computing (Internet of Things, Augmented Reality, Cloud Computing).",
    4 : "Sesuai dengan namanya, lisensi commercial ini dibuat untuk semua software yang tujuannya untuk komersial alias jualan. Maka dari itu, untuk dapat menggunakan software atau aplikasi yang memiliki lisensi commercial, dia harus membelinya atau bisa juga dengan mendapatkan izin dari sang pemilik hak cipta software atau aplikasi tersebut. Contoh paling mudah untuk software lisensi commercial ini di antaranya Sistem Operasi Windows yang dibuat Microsoft.",
    5 : "Valorant merupakan panduan gaya dan pengalamanmu di panggung kompetitif global. Kamu diberi 13 ronde untuk menyerang dan mempertahankan sisimu dengan keahlian tembak-menembak sengit dan kemampuan taktis. Dengan satu nyawa per ronde, kamu harus berpikir lebih cepat daripada lawan jika ingin tetap hidup. Habisi musuh baik di mode Competitive maupun Tanpa Rank serta Deathmatch dan Spike Rush. Lebih dari sekadar senjata dan peluru, kamu akan memilih Agen bersenjatakan kemampuan yang adaptif, tangkas, dan mematikan untuk membuktikan keahlian menembakmu. Sebagaimana tiap sidik jari selalu berbeda, begitu pula di sini; tak akan ada Agen dengan karakteristik sama.Tiap peta adalah panggung tersendiri untuk memamerkan kemampuan berpikir kreatifmu. Dirancang sesuai untuk strategi tim, laga spektakuler, dan momen sengit. Perlihatkan kepiawaian yang akan ditiru oleh pemain lain sampai bertahun-tahun mendatang.",
    6 : "Rolls Royce Cullinan merupakan jenis mobil SUV yang mampu menjelajah di semua medan. Namun, mobil ini tetap dilengkapi interior yang sangat mewah. SUV mewah ini diprediksi mampu melaju hingga kecepatan 155 mph atau setara 249 km/jam.",
    7 : "Rolls Royce Phantom adalah model mobil sedan premium yang memiliki konfigurasi empat pintu. Mobil yang satu ini memiliki sejarah yang cukup panjang dalam perkembangan Rolls Royce. Generasi pertama dari Rolls Royce Phantom dirilis pada tahun 1925 silam. Pada perjalanannya di dunia otomotif, Rolls Royce akhirnya diakuisisi oleh BMW."
}